server:
  port: 3331

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:3000'
              - 'http://advisor.silvertale.xyz'

        allowCredentials: true # 요청시 인증정보 전송 허가
        allowedHeaders: '*'
        allowedMethods: '*'
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/v1/member/**
          filters:
            - RewritePath=/api/v1/member/?(?<path>.*),/$\{path}
        - id: member-data
          uri: lb://member-data
          predicates:
            - Path=/api/v1/service/**
          filters:
            - RewritePath=/api/v1/service/?(?<path>.*),/$\{path}
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/v1/board/**
          filters:
            - RewritePath=/api/v1/board/?(?<path>.*),/$\{path}
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/file/**
          filters:
            - RewritePath=/api/v1/file/?(?<path>.*),/$\{path}
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/v1/email/**
          filters:
            - RewritePath=/api/v1/email/?(?<path>.*),/$\{path}
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/v1/message/**
          filters:
            - RewritePath=/api/v1/message/?(?<path>.*),/$\{path}

# 유레카 설정
eureka:
  instance:
    hostname: ${hostname}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.server}/eureka/

# 액츄에이터 설정
management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway